# Generated by Django 3.2.9 on 2021-11-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, null=True)),
                ('code', models.CharField(default=None, max_length=255, null=True)),
                ('selling_price', models.IntegerField(default=None, max_length=100, null=True)),
            ],
        ),
    ]
